import { useState, useEffect } from "react";
import { Link, useOutletContext } from "react-router";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Trash2, FileText, Calendar, BookOpen, Plus, Edit } from "lucide-react";
import { categories } from "../data/mockData";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "../components/ui/alert-dialog";

interface OutletContext {
  expertMode: boolean;
}

export interface SavedLessonPlan {
  id: string;
  title: string;
  description: string;
  selectedCategory: string;
  selectedWords: string[];
  notes: string;
  createdAt: string;
}

export function SavedLessonPlansPage() {
  const { expertMode } = useOutletContext<OutletContext>();
  const [lessonPlans, setLessonPlans] = useState<SavedLessonPlan[]>([]);
  const [planToDelete, setPlanToDelete] = useState<string | null>(null);

  useEffect(() => {
    loadLessonPlans();
  }, []);

  const loadLessonPlans = () => {
    try {
      const saved = localStorage.getItem("cree-lesson-plans");
      if (saved) {
        const plans = JSON.parse(saved) as SavedLessonPlan[];
        // Sort by created date, newest first
        plans.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        setLessonPlans(plans);
      }
    } catch (error) {
      console.error("Failed to load lesson plans:", error);
    }
  };

  const handleDelete = (id: string) => {
    try {
      const updated = lessonPlans.filter(plan => plan.id !== id);
      localStorage.setItem("cree-lesson-plans", JSON.stringify(updated));
      setLessonPlans(updated);
      setPlanToDelete(null);
    } catch (error) {
      console.error("Failed to delete lesson plan:", error);
    }
  };

  const handleExportPrintable = (plan: SavedLessonPlan) => {
    const selectedCategory = categories.find(c => c.id === plan.selectedCategory);

    let content = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${plan.title || 'Lesson Plan'}</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
          h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
          h2 { color: #4b5563; margin-top: 30px; }
          .word-count { color: #6b7280; font-size: 14px; }
          .notes { background: #f3f4f6; padding: 15px; border-radius: 8px; margin-top: 20px; }
          @media print { body { margin: 0; } }
        </style>
      </head>
      <body>
        <h1>${plan.title || 'Cree Language Lesson Plan'}</h1>
        ${plan.description ? `<p><strong>Description:</strong> ${plan.description}</p>` : ''}
        ${selectedCategory ? `<p><strong>Category:</strong> ${selectedCategory.name} (${selectedCategory.cree})</p>` : ''}

        <h2>Vocabulary</h2>
        <p class="word-count">${plan.selectedWords.length} words selected</p>

        ${plan.notes ? `
          <h2>Notes</h2>
          <div class="notes">${plan.notes.replace(/\n/g, '<br>')}</div>
        ` : ''}

        <p style="margin-top: 40px; color: #9ca3af; font-size: 12px;">
          Generated by Vocabulary Explorer • ${new Date(plan.createdAt).toLocaleDateString()}
        </p>
      </body>
      </html>
    `;

    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${plan.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  return (
    <div className="p-4 max-w-4xl mx-auto pb-6">
      <div className="flex items-start justify-between gap-3 mb-6">
        <div className="flex-1 min-w-0">
          <h2 className="text-xl sm:text-2xl font-bold mb-2">My Lesson Plans</h2>
          <p className="text-sm sm:text-base text-gray-600">
            View and manage your saved lesson plans
          </p>
        </div>
        <Link to="/lesson-plan">
          <Button size="sm" className="touch-manipulation whitespace-nowrap">
            <Plus className="w-4 h-4 mr-1 sm:mr-2" />
            <span className="hidden sm:inline">Create New</span>
            <span className="sm:hidden">New</span>
          </Button>
        </Link>
      </div>

      {lessonPlans.length === 0 ? (
        <Card>
          <CardContent className="p-12 text-center">
            <BookOpen className="w-16 h-16 mx-auto mb-4 text-gray-400" />
            <h3 className="text-lg font-semibold mb-2">No Lesson Plans Yet</h3>
            <p className="text-gray-600 mb-4">
              Create your first lesson plan to get started
            </p>
            <Link to="/lesson-plan">
              <Button className="touch-manipulation">
                <Plus className="w-4 h-4 mr-2" />
                Create Lesson Plan
              </Button>
            </Link>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {lessonPlans.map((plan) => {
            const category = categories.find(c => c.id === plan.selectedCategory);
            return (
              <Card key={plan.id} className="hover:shadow-md transition-shadow">
                <CardHeader>
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex-1">
                      <CardTitle className="text-lg mb-2">{plan.title}</CardTitle>
                      {plan.description && (
                        <p className="text-sm text-gray-600 mb-3">{plan.description}</p>
                      )}
                      <div className="flex flex-wrap gap-2">
                        {category && (
                          <Badge variant="outline">
                            {category.name}
                          </Badge>
                        )}
                        <Badge variant="secondary">
                          {plan.selectedWords.length} words
                        </Badge>
                        {plan.notes && (
                          <Badge variant="secondary">
                            Has notes
                          </Badge>
                        )}
                      </div>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <Link to={`/lesson-plan?edit=${plan.id}`}>
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-9 w-9 p-0 touch-manipulation"
                        >
                          <Edit className="w-4 h-4" />
                        </Button>
                      </Link>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleExportPrintable(plan)}
                        className="h-9 w-9 p-0 touch-manipulation"
                      >
                        <FileText className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setPlanToDelete(plan.id)}
                        className="h-9 w-9 p-0 touch-manipulation"
                      >
                        <Trash2 className="w-4 h-4 text-red-500" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-2 text-xs text-gray-500">
                    <Calendar className="w-3 h-3" />
                    <span>Created {formatDate(plan.createdAt)}</span>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!planToDelete} onOpenChange={() => setPlanToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Lesson Plan</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this lesson plan? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => planToDelete && handleDelete(planToDelete)}
              className="bg-red-600 hover:bg-red-700"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
